version: '3.8'

services:
  postgres:
    image: postgres:16.2-bookworm
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: heisen-flow
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_USER: root
      DB_PASS: 123456
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: heisen-flow

volumes:
  postgres-data: