openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /items:
    get:
      summary: api v1
      responses:
        '200':
          description: Creating Users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
